### ISSUE TITLE
minimalmodbus.NoResponseError: No communication with the instrument (no answer)

### ISSUE THREAD

**Issue by rikhsitlladeveloper** [nexus1203/KincoServo#1]
Hello  I have kinco ac servo fd124s driver and I can not use it with this code as well 
here is my error
I used RS485 to USB converter 
minimalmodbus.NoResponseError: No communication with the instrument (no answer)

**Comment by nexus1203** [comment]
Can you set the baud rate to 115200 in servo driver rs485 communication settings and try again? Because in my code I have fixed the communication rate. however you also need to find which COM port the RS485 to USB is connected. This you can check in the windows device manager.

**Comment by nexus1203** [comment]
@rikhsitlladeveloper  has the problem been resolved? If you experience any other problems regarding this library you may open another issue. As of this I am assuming it resolved due to inactivity. Thank you.
